spring:
  thymeleaf:
    # 关闭缓存
    cache: false


  # redis配置
  redis:
    host: 127.0.0.1
    # 端口
    port: 6379
    # 数据库
    database: 0
    #超时时间
    connect-timeout: 10000ms
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 8
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms

        # 最大空闲连接，默认8
        max-idle: 200
        #最小空闲连接，默认0
        min-idle: 5

  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        default-requeue-rejected: true
        auto-startup: true

    template:
      retry:
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms
        multiplier: 1
        enabled: true
    virtual-host: /



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1027548565ABC
    # 连接池
    hikari:
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲链接存活最大时间，默认600000（10分钟）
      idle-timeout: 1800000
      # 最大链接数,默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 链接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试链接是否可用的查询语句
      connection-test-query: SELECT 1
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        cache control:
          max-age: 3600
      add-mappings: true
      chain:
        cache: true
        enabled: true
        compressed: true

mybatis-plus:
  # 配置Mapper.xml 映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.zzy.seckill.entity



# MyBatis SQL打印（方法接口所在的包，不是Mappler.xml所在的包）
logging:
  level:
    com.zzy.seckill.mapper: debug